import { useCallback, useState } from 'react';
import { Alert, Image, Linking, ScrollView, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { BriefcaseBusiness, CalendarDays, ExternalLink, Github, GraduationCap, MapPin, Pencil, Phone, Trash2 } from 'lucide-react-native';
import Toast from 'react-native-toast-message';
import LoadingSpinner from '../components/LoadingSpinner';
import CustomButton from '../components/CustomButton';
import { studentService } from '../services/studentService';

function initials(name = '') { return name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); }
function Detail({ icon: Icon, label, value }) { return value ? <View className="flex-row gap-3 py-3"><Icon size={18} color="#64748B" /><View className="flex-1"><Text className="text-xs font-medium uppercase text-muted">{label}</Text><Text className="mt-1 text-sm text-ink">{value}</Text></View></View> : null; }
function TagGroup({ title, tags }) { return tags?.length ? <View className="mt-6"><Text className="text-base font-semibold text-ink">{title}</Text><View className="mt-3 flex-row flex-wrap gap-2">{tags.map((tag) => <View key={tag} className="rounded-full bg-indigo-50 px-3 py-1.5"><Text className="text-sm font-medium text-brand">{tag}</Text></View>)}</View></View> : null; }

export default function StudentProfileScreen({ navigation }) {
  const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [deleting, setDeleting] = useState(false);
  const load = useCallback(async () => { try { const response = await studentService.mine(); setProfile(response.data); } catch (error) { Toast.show({ type: 'error', text1: 'Could not load profile', text2: error.message }); navigation.goBack(); } finally { setLoading(false); } }, [navigation]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  async function remove() { try { setDeleting(true); await studentService.remove(profile._id); Toast.show({ type: 'success', text1: 'Profile deleted' }); navigation.goBack(); } catch (error) { Toast.show({ type: 'error', text1: 'Could not delete profile', text2: error.message }); } finally { setDeleting(false); } }
  function confirmDelete() { Alert.alert('Delete student profile?', 'This action cannot be undone. Your account will remain available.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete profile', style: 'destructive', onPress: remove }]); }
  if (loading) return <LoadingSpinner />;
  const birthday = profile.birthday ? new Date(profile.birthday).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }) : '';
  return <ScrollView className="flex-1 bg-canvas" contentContainerClassName="pb-10"><View className="items-center bg-white px-5 pb-7 pt-8"><View className="h-24 w-24 items-center justify-center overflow-hidden rounded-full bg-indigo-100">{profile.profileImage ? <Image source={{ uri: profile.profileImage }} className="h-24 w-24" /> : <Text className="text-3xl font-bold text-brand">{initials(profile.fullName)}</Text>}</View><Text className="mt-4 text-2xl font-bold text-ink">{profile.fullName}</Text><Text className="mt-1 text-sm text-muted">{profile.degree || 'Student'}{profile.department ? ` · ${profile.department}` : ''}</Text><View className="mt-5 w-full"><CustomButton title="Edit profile" onPress={() => navigation.navigate('StudentForm', { profile })} icon={Pencil} /></View></View><View className="px-5 pt-6"><View className="rounded-lg border border-slate-200 bg-white px-4"><Detail icon={Phone} label="Phone" value={profile.phoneNumber} /><Detail icon={CalendarDays} label="Birthday" value={birthday} /><Detail icon={GraduationCap} label="Education" value={[profile.school, profile.faculty, profile.studentId && `ID ${profile.studentId}`].filter(Boolean).join('\n')} /><Detail icon={MapPin} label="Location" value={[profile.city, profile.province, profile.country].filter(Boolean).join(', ')} /><Detail icon={BriefcaseBusiness} label="Career interests" value={profile.careerInterests} /></View>{profile.bio ? <View className="mt-6"><Text className="text-base font-semibold text-ink">About</Text><Text className="mt-2 text-sm leading-6 text-muted">{profile.bio}</Text></View> : null}<TagGroup title="Skills" tags={profile.skills} /><TagGroup title="Hobbies & interests" tags={profile.hobbies} />{(profile.linkedin || profile.github) ? <View className="mt-7"><Text className="mb-3 text-base font-semibold text-ink">Links</Text>{profile.linkedin ? <CustomButton title="Open LinkedIn" variant="outline" onPress={() => Linking.openURL(profile.linkedin)} icon={ExternalLink} /> : null}{profile.github ? <View className="mt-3"><CustomButton title="Open GitHub" variant="outline" onPress={() => Linking.openURL(profile.github)} icon={Github} /></View> : null}</View> : null}<View className="mt-8"><CustomButton title="Delete profile" variant="danger" onPress={confirmDelete} loading={deleting} icon={Trash2} /></View></View></ScrollView>;
}

